### ISSUE TITLE
units of temperature coefficient

### ISSUE THREAD

**Issue by wholmgren** [SolarPerformanceInsight/solarperformanceinsight#106]
SPI currently uses temperature coefficients in units of per degree C, like pvlib.

In the Solar Forecast Arbiter project we changed to %/C based on stakeholder feedback. 

Should we do the same for SPI?

**Comment by cwhanse** [comment]
I think yes.

**Comment by alorenzo175** [comment]
We should keep the pvsyst `mu_gamma` in units of 1/K right?

**Comment by cwhanse** [comment]
> We should keep the pvsyst `mu_gamma` in units of 1/K right?

Yes
