### ISSUE TITLE
support CEC module lookup, ModelChain(dc_model='cec')

### ISSUE THREAD

**Issue by wholmgren** [SolarPerformanceInsight/solarperformanceinsight#135]
Extracting the issue from #110:

@ncroft-b4 says

> Can there be a module lookup like there is an inverter lookup? I found the tags for the module parameters in the system creation confusing. I was trying to use a module from the SAM CEC database, LG395N2W-A5. The tags in SPI (Gamma Ref, Mu Gamma, etc) did not seem consistent with the data in the cec module database that is retrievable in pvlib. In particular, Gamma Ref is a_ref in the database, and Mu Gamma and R SH 0 are not in the database. In the end, the computation on my system did not produce positive energy, possibly to do with some mistake in these parameters that I made.

Followed by @alorenzo175 @cwhanse clarification that the CEC module definitions are similar to but not compatible with the PVSyst definitions. 

To support this we'll need to make changes to the front end system definitions and the back end python modeling. 

For the typescript/vue front end, we need to:

1. Define a new model type for the system metadata page. I guess I'd call it CEC but I don't know if that's a user friendly name.
2. copy/modify [`PVSystModuleParameters`](https://github.com/SolarPerformanceInsight/solarperformanceinsight/blob/b83658605d4a32dfd5ef8c78533c35252f38f30c/dashboard/src/types/ModuleParameters.ts#L1-L56)
3. update allowed types in [`PVArray`](https://github.com/SolarPerformanceInsight/solarperformanceinsight/blob/b83658605d4a32dfd5ef8c78533c35252f38f30c/dashboard/src/types/PVArray.ts)
4. Change a handful of `v-if="model == 'pvsyst'"` to either a) != 'pvwatts'. or b) == 'pvsyst' or == 'cec'
5. hook up module look up feature

For the python back end, we need to:

1. copy/modify [`PVsystModuleParameters`](https://github.com/SolarPerformanceInsight/solarperformanceinsight/blob/b83658605d4a32dfd5ef8c78533c35252f38f30c/api/solarperformanceinsight_api/models.py#L152-L205)
2. change [`PVArray.module_parameters` type annotation](https://github.com/SolarPerformanceInsight/solarperformanceinsight/blob/b83658605d4a32dfd5ef8c78533c35252f38f30c/api/solarperformanceinsight_api/models.py#L273)

@cwhanse you can start a PR with at least the python and let @lboeman take it over when you're stuck.

**Comment by alorenzo175** [comment]
closed by #149
