### ISSUE TITLE
Add dashboard system management page

### ISSUE THREAD

**Issue by lboeman** [SolarPerformanceInsight/solarperformanceinsight#15]
The dashboard will need a site management page. I imagine this will be the central navigation for the dashboard, with a few features.
- Define a new system.
- Delete/update/clone systems.
- Select a system to start a calculation workflow. 

This can be implemented with some test data but the eventual api requirements will be something like:
- System metadata list endpoint (probably just some summary/identifying information like name and id)
- System metadata creation endpoint
- System deletion endpoint.

**Comment by wholmgren** [comment]
@lboeman can we close this, perhaps opening a new issue for a clone feature with milestone "someday"?
