### ISSUE TITLE
Confusing Note about Single Axis

### ISSUE THREAD

**Issue by ncroft-b4** [SolarPerformanceInsight/solarperformanceinsight#155]
Minor cosmetic issue: When building a multi-array system, when a second array is added a note pops up next to the tracking selection as below. 
![image](https://user-images.githubusercontent.com/57274570/109363737-7e7d8380-784a-11eb-9fe4-b9433347a107.png)

This appears as if I have made a wrong selection, even though I believe the note is meant to refer to the Single Axis option (Single axis was appropriately not selectable) . But it required me to hit save and move on from making the system with large red text hanging out on the screen, which felt wrong. 

Perhaps leave out this warning, as Single Axis was not selectable, or make it only appear if an attempt is made to click Single Axis and have it go way if Fixed is clicked, if possible. Or even putting it in parentheses and making it black, as that could make it more clear it is to be grouped with Single Axis and explains why it is not selectable.
![image](https://user-images.githubusercontent.com/57274570/109364279-a8837580-784b-11eb-8659-cd9c75e50890.png)

**Comment by wholmgren** [comment]
I had the same reaction when working through a system earlier today. My hope is that the relevant pvlib work (https://github.com/pvlib/pvlib-python/pull/1146 or https://github.com/pvlib/pvlib-python/pull/1176) will be finished soon enough that we can remove the restriction before we need to clarify this for other users.
