### ISSUE TITLE
Add Power units to upload mapping process

### ISSUE THREAD

**Issue by lboeman** [SolarPerformanceInsight/solarperformanceinsight#98]
Allow users to define what units they have in their data files. This will allow us to nail down expected units at the API for simpler code there. Conversion to expected base units before API submission. Users should also be able to select units on the results page as well, so standalone conversion functions are a good idea.

**Comment by alorenzo175** [comment]
Will definitely need this for the 2abc cases since people are unlikely to start with data in watts

**Comment by lboeman** [comment]
Ideally unit conversion code will extend to displaying resulting values and plots in the desired units. Should this also convert values in downloaded data as well?

**Comment by wholmgren** [comment]
> Should this also convert values in downloaded data as well?

I think we all agreed this was not necessary and it would be extra work because it would require an API feature instead of just a dashboard feature.
